FROM postgres:17
RUN apt-get update \
    && apt-get install -y postgresql-17-pgaudit \
    && rm -rf /var/lib/apt/lists/*

COPY init-log-dir.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/init-log-dir.sh