FROM postgres:17
RUN apt-get update \
    && apt-get install -y postgresql-17-pgaudit \
    && rm -rf /var/lib/apt/lists/*
COPY fix-perms-entrypoint.sh /fix-perms-entrypoint.sh
RUN chmod +x /fix-perms-entrypoint.sh
COPY 01-init-pgaudit.sql /docker-entrypoint-initdb.d/
ENTRYPOINT ["/fix-perms-entrypoint.sh"]
CMD ["postgres"]