"""SQL rewriter by AST, used by the Streamlit app.

The rewriter injects provenance annotations into SELECT queries so that the UI can
render lineage intervals alongside each result row. 

rewrite_sql() is the entry point to this module and is the only recommended way to use it.
"""

import datetime

from pglast import parse_sql
from pglast.stream import RawStream
from pglast.ast import Alias, ColumnRef, FuncCall, RangeSubselect, ResTarget, SelectStmt, String
from pglast.visitors import Visitor


class AstRewriter(Visitor):
    def __init__(self, window_start: datetime.datetime, window_end: datetime.datetime, schema: dict):
        """Store the provenance window and table schema for rewriting."""
        super().__init__()
        self.window_start = window_start
        self.window_end = window_end
        self.schema = schema

    def visit_RangeVar(self, ancestors, node):
        """Intercepts references to tables found in self.schema and replaces each table with a parsed subquery generated by scan()."""
        if node.relname in self.schema:
            return RangeSubselect(
                subquery=parse_sql(scan(
                    node.relname, self.schema[node.relname], self.window_start, self.window_end))[0],
                alias=node.alias if node.alias else Alias(
                    aliasname=node.relname)
            )
        else:
            raise ValueError(
                f"Table '{node.relname}' missing from schema. "
                f"Expected one of: {list(self.schema.keys())}"
            )

    def visit_SelectStmt(self, ancestors, node):
        """Append the annotation column to each SELECT list.
        Known bug: may duplicate the annotation column, notably if target is A_Star."""
        target_list = list(node.targetList or [])

        if node.groupClause:  # Trigger custom aggregation for annotation under alternate use
            val = FuncCall(
                funcname=(String("add_annotations"),),
                args=(ColumnRef(fields=["annotation"]),)
            )
        else:
            val = ColumnRef(fields=["annotation"])

        target_list.append(
            ResTarget(
                name="annotation",
                val=val
            )
        )
        node.targetList = tuple(target_list)

    def visit_JoinExpr(self, ancestors, node):
        """Rewrite ancestor targets so joins combine lineage from both sides."""
        left_name = node.larg.alias if node.larg.alias else node.larg.relname
        right_name = node.rarg.alias if node.rarg.alias else node.rarg.relname

        select_node = ancestors
        while select_node is not None and not isinstance(select_node.node, SelectStmt):
            select_node = select_node.parent
        select_node = select_node.node  # should be safe :)

        new_targets = []
        for t in (select_node.targetList or []):
            col = t.val.fields[-1] if hasattr(t.val, 'fields') else None
            if t.name == "annotation" or col == "annotation":
                join_func = FuncCall(
                    funcname=(String("join_annotations"),),
                    args=(
                        ColumnRef(fields=(left_name, "annotation")),
                        ColumnRef(fields=(right_name, "annotation")),
                    )
                )
                if isinstance(t.val, FuncCall) and t.val.funcname[0].sval == "add_annotations":
                    t.val.args = (join_func,)
                    new_targets.append(t)
                else:
                    new_targets.append(ResTarget(
                        name="annotation",
                        val=join_func
                    ))
            else:
                new_targets.append(t)

        select_node.targetList = tuple(new_targets)


# TODO: check if we can get rid of the window_end? because it's kinda hard tied to current
def rewrite_sql(sql_string: str, window_start: datetime.datetime, window_end: datetime.datetime, schema: dict) -> str:
    """Rewrites the input SQL query to include provenance annotations based on the given time window and schema. Entry point to this module.
    Args:
        sql_string: The input SQL query as a string. All referenced tables must be present in the schema.
        window_start: The start of the time window for provenance tracking.
        window_end: The end of the time window for provenance tracking.
        schema: A dictionary mapping table names to their column names (excluding 'id' and 'death').
    Returns:
        The rewritten SQL query as a string.
    """
    tree = parse_sql(sql_string)[0].stmt
    AstRewriter(window_start, window_end, schema)(tree)
    return RawStream()(tree)


def scan(table_name, columns, window_start, window_end):
    """
    Generate a SQL query that scans `table_name` and attaches provenance
    annotations to each row.

    The generated query:
      - projects the specified columns - note that only columns id and death are projected away under standard usage
      - filters out tuples whose lifetime do not overlap with the time window,
      - joins matching audit log entries within
        [`window_start`, `window_end`], and
      - aggregates them into an `annotation` JSONB column.

    The `annotation` column is a JSON array of provenance annotations. Each
    annotation has the form [[blameframe...]...], where each blameframe has the structure:
        {
            "birth": [<positive log entries>] | null,
            "death": [<negative log entries>] | null,
            "interval": [start_timestamp, end_timestamp]
        }

    Args:
        table_name: Name of the table to scan.
        columns: Columns to project.
        window_start: Inclusive start of the annotation window.
        window_end: Inclusive end of the annotation window.

    Returns:
        A SQL query string.
    """
    cols = ", ".join(columns)

    return f"""
            SELECT {cols}, 
                jsonb_build_array(annotate_agg(tmp.blame::jsonb, tmp.pos_neg, tmp.ts ORDER BY tmp.ts)) AS annotation
            FROM (
                SELECT *
                FROM {table_name} t
                    LEFT JOIN (
                        SELECT row_id, row_to_json(a) as blame, ts, pos_neg
                        FROM audit_log a
                        WHERE a.table_name = '{table_name}'
                            AND a.ts >= '{window_start}'
                            AND a.ts <= '{window_end}'
                        ) as a ON a.row_id = t.id
                WHERE t.death > '{window_start}'                       
            ) AS tmp
            GROUP BY {cols}
            """
